DROP TABLE IF EXISTS products CASCADE;
CREATE TABLE products (
id SERIAL PRIMARY KEY NOT NULL,
type_id INTEGER REFERENCES product_types(id) ON DELETE CASCADE,
name VARCHAR (255) NOT NULL,
is_available BOOLEAN DEFAULT TRUE,
description VARCHAR(255),
photo_1 TEXT,
price INTEGER NOT NULL,
is_featured BOOLEAN DEFAULT TRUE
);
